### ISSUE TITLE
Design of service registry state

### ISSUE THREAD

**Issue by coopernurse** [simia-tech/rust-delix#13]
This is a placeholder to discuss how Delix will store routing information mapping service names with the processes that implement each service.

Iris stored this information in a DHT, but I was never clear on the consistency and fault tolerance properties of the cluster.  For example, what happens if a member of a Delix cluster fails and is then restarted?

**Comment by phifty** [comment]
Well, in the current `Direct` implementation, every node simply stores a complete service registry. Have a look at src/transport/direct/{direct.rs, service_map.rs}. I hope the code is somehow understandable.

The service map is updated as follows:
- When a node joins the network, it receives a service list from all nodes it connects to (that are all nodes of the network). 
- When a service is registered, the information is send to all connected nodes.
- When a service is deregistered, this is not communicated. Services are removed if a request to it returned a `ServiceDoesNotExists` error. This is not completely implemented yet.
- When a connection is lost, the related services are removed from the service map.

**Comment by coopernurse** [comment]
Ok, that sounds pretty simple, but I'm a little worried about network partitions.  For example, if a node becomes isolated it may miss the registration messages from its peers, and will begin removing existing services from its local service map (because of connection failures).  When the network partition heals, this node will have an incomplete view of the cluster.

We could implement a heartbeat message between peers that includes a checksum of the service map.  If any peers disagree then they could rebroadcast the list of services registered locally.

If you think that's a good idea, we can open a separate issue for it.

**Comment by phifty** [comment]
Good point. To be honest, I haven't thought about that ;-)

But if I think about it now, I would say - unless I miss something - it shouldn't be a problem. If a connection is lost, there is currently no recover algorithm implemented. So a connection is currently lost for good. Partition healing would involve the restart of a node to make it re-join the network. The join process includes a re-transmit of the service map. Afterwards, the service map should be up to date. I my eyes this is good enough for the first version.

In later versions, a connection recovery should be implemented of course. The recovery should then include a transmission and merge of the service map. This would solve than also the network partition problem.
