### ISSUE TITLE
Add TravisCI or CircleCI

### ISSUE THREAD

**Issue by coopernurse** [simia-tech/rust-delix#19]
Configure automatic build/test from master branch with one of these services.

I don't have a preference -- both are free for public repos.

Thoughts?

**Comment by phifty** [comment]
I'm in for CI. Does CircleCI support Rust? I don't find it in the docs.

**Comment by coopernurse** [comment]
TravisCI has clear Rust instructions, so let's try that:

https://docs.travis-ci.com/user/languages/rust

I'm testing on my fork now - will issue a PR with the change in a moment.
